version: "3.9"
services:

  database:
    container_name: kupipodariday-postgres
    image: "postgres:12"
    networks:
      - kupipodariday-db 
    ports:
      - "5432:5432"
    volumes:
      - ./volume:/var/lib/postgresql/data
    env_file: ./backend/.env
    restart: unless-stopped

  backend:
    container_name: kupipodariday-backend
    build: ./backend
    env_file: ./backend/.env
    restart: "unless-stopped"
    ports:
      - "4000:3000"
    networks:
      - kupipodariday-network
      - kupipodariday-db
    links:
      - database
    depends_on:
      - database

  frontend:
    container_name: kupipodariday-frontend
    build: ./frontend
    ports:
      - 8081:80
    networks:
      - kupipodariday-network
      - kupipodariday-db


volumes:
  volume:
    external: true

networks:
  kupipodariday-db: 
    driver: bridge
  kupipodariday-network:
    driver: bridge
